### ISSUE TITLE
move to manjaro

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-icons#1]
@Kirek @philmmanjaro , can we please move this to manjaro repos,
and also [this one](https://github.com/oberon2007/manjaro-backgrounds) ?
Thanks.

**Comment by Huluti** [comment]
@philmmanjaro And [this one now](https://github.com/oberon2007/manjaro-wallpapers-17.0).

**Comment by Huluti** [comment]
It would be nice to have all the official rest in the official Manjaro depots to properly represent the state of the packages.

**Comment by jonathonf** [comment]
I think the repo owner can transfer ownership to a different user/organisation: https://help.github.com/articles/transferring-a-repository/

**Comment by oberon2007** [comment]
https://github.com/manjaro/manjaro-icons
done.

**Comment by Huluti** [comment]
Good 👍 There is also this one : https://github.com/oberon2007/manjaro-wallpapers-17.0
